name: Setup
runs:
  using: "composite"
  steps:
    - name: Install Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0
        cache: npm
        registry-url: "https://registry.npmjs.org"

    - name: Turbo Cache
      id: turbo-cache
      uses: actions/cache@v2
      with:
        path: .turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - name: Install
      env:
        CI: true
      shell: bash
      run: |
        npm install
