name: Add Sponsor Labels

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened, edited]

jobs:
  build:
    name: Label Sponsors
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/is-sponsor-label-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
